### ISSUE TITLE
Easier way

### ISSUE THREAD

**Issue by gingerbeardman** [rovest/ulysses_snapshot#2]
1. Ulysses > File > Add External Folder...
2. Choose local folder
3. Select all your Ulysses Groups
4. Alt+Drag your groups to local folder (Alt makes sure to copy not move)
5. Local folder will now contain a readable, structured copy of your groups

**Comment by rovest** [comment]
@gingerbeardman Yes, that's much easier :)

Since external folders evolved with support for textbundle, DB external folders on iOS, etc., this project may have become obsolete for most people.

On the other hand, `ulysses_snapshot.py` can be run automatically from a cron job (with `ul_sync_md.py`) exporting from iCloud and OnMy Mac libs, checking for changes every 5 min, every hour, or whatever anyone would need. Also exported markdown from `ulysses_snapshot.py` contains MD-XL attachment info, inline, and block comments as well. Original modified time is also preserved.

If none of this is needed, your solution is much simpler and better.
